function required(doc, selector) {
  const node = doc.querySelector(selector);
  if (!node) throw new Error(`Falta el elemento ${selector} en la página.`);
  return node;
}

export function queryApp(doc) {
  return {
    petCount: required(doc, '#pet-count'),
    petGrid: required(doc, '#pet-grid'),
    searchInput: required(doc, '#pet-search'),
    resultsCount: required(doc, '#results-count'),
    emptyState: required(doc, '#empty-state'),
    savedFilter: required(doc, '#saved-filter'),
    savedCount: required(doc, '#saved-count'),
    adoptionDialog: required(doc, '#adoption-dialog'),
    adoptionForm: required(doc, '#adoption-form'),
    dialogFormView: required(doc, '#dialog-form-view'),
    dialogSuccess: required(doc, '#dialog-success'),
    authDialog: required(doc, '#auth-dialog'),
    authTrigger: required(doc, '#auth-trigger'),
    loginForm: required(doc, '#login-form'),
    registerForm: required(doc, '#register-form'),
    forgotPassword: required(doc, '#forgot-password'),
    authFeedback: required(doc, '#auth-feedback'),
    authToast: required(doc, '#auth-toast'),
    themeToggle: required(doc, '#theme-toggle'),
    statsAvailable: required(doc, '#stats-available'),
    statsRequests: required(doc, '#stats-requests'),
    statsFamilies: required(doc, '#stats-families'),
    recommendationGrid: required(doc, '#recommendation-grid'),
    trackingDialog: required(doc, '#tracking-dialog'),
    trackingList: required(doc, '#tracking-list'),
    petDetailDialog: required(doc, '#pet-detail-dialog'),
    petDetailTitle: required(doc, '#pet-detail-title'),
    petDetailBreed: required(doc, '#pet-detail-breed'),
    petDetailImage: required(doc, '#pet-detail-image'),
    petDetailStatus: required(doc, '#pet-detail-status'),
    petDetailTags: required(doc, '#pet-detail-tags'),
    petDetailDescription: required(doc, '#pet-detail-description'),
    petDetailAge: required(doc, '#pet-detail-age'),
    petDetailSpecies: required(doc, '#pet-detail-species'),
    petDetailFavorite: required(doc, '#pet-detail-favorite'),
    petDetailAdopt: required(doc, '#pet-detail-adopt'),
    refugeDialog: required(doc, '#refuge-dialog'),
    managedPets: required(doc, '#managed-pets'),
    managedRequests: required(doc, '#managed-requests'),
    petCreateForm: required(doc, '#pet-create-form'),
    petFormFeedback: required(doc, '#pet-form-feedback'),
    compatibilityDialog: required(doc, '#compatibility-dialog'),
    compatibilityForm: required(doc, '#compatibility-form'),
    quizFormView: required(doc, '#quiz-form-view'),
    quizResult: required(doc, '#quiz-result'),
    quizResultList: required(doc, '#quiz-result-list'),
    refugeMapElement: required(doc, '#refuge-map'),
    refugeList: required(doc, '#refuge-list'),
    filterGroup: required(doc, '.filter-group'),
    ageFilters: required(doc, '#age-filters'),
    sizeFilters: required(doc, '#size-filters'),
    resetSearch: required(doc, '#reset-search'),
    applicationSummary: required(doc, '#application-summary'),
    panelRequestCount: required(doc, '#panel-request-count')
  };
}
